export const CART_PRODUCT_REQUEST = "CART_PRODUCT_REQUEST"
export const CART_PRODUCT_REQUEST_FAIL = "CART_PRODUCT_REQUEST_FAIL"

export const GET_CART_PRODUCT_REQUEST_SUCCESS = "GET_CART_PRODUCT_REQUEST_SUCCESS"

export const POST_CART_REQUEST_SUCCESS = "POST_CART_REQUEST_SUCCESS"

export const UPDATE_CART_REQUEST_SUCCESS = "UPDATE_CART_REQUEST_SUCCESS"


export const DELETE_CART_REQUEST_SUCCESS = "DELETE_CART_REQUEST_SUCCESS"

export const UPDATE_CART_TO_EMPTY = "UPDATE_CART_TO_EMPTY"