export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_REQUEST_FAIL = "LOGIN_REQUEST_FAIL"
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS"
export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_REQUEST_FAIL = "REGISTER_REQUEST_FAIL"
export const REGISTER_REQUEST_SUCCESS = "REGISTER_REQUEST_SUCCESS"

export const LOGOUT_REQUEST_SUCCESS = "LOGOUT_REQUEST_SUCCESS"